### PR TITLE
Nunit3 support and disallow construct "using ;"'s

### PR DESCRIPTION
**Pull request by eugeneai**
Hi!

1. My site generated code "using ;" for an empty namespace. So I disallowed it to do so.
2. I needed to generate a debug version of SharpTAL, and I had to study C Sharp infrastructure and NUnit3. Meanwhile, I've adapted Your project to it.

Best Regards,
Evgeny

### CODE REVIEW

**Comment by lck** [comment]
Hi Evgeny!
thank you for your contrbution. Please can you update the Docs/CHANGES.rst file and don't forget to add your credits. Let me know when you are done (no other changes will be commited to tjis pull req) and I will review and merge.
Regards
Roman

**Comment by eugeneai** [comment]
Ok.
I have filled in the contribution.

Best regards,
Evgeny

**Comment by eugeneai** [comment]
Ok. Everything id ready to be reviewed.

**Comment by lck** [comment]
Merged, thanks for your contribution!

**Pull request merged**
